### ISSUE TITLE
探讨：北京等城市地震有什么好办法获取到及时的预警数据不

### ISSUE THREAD

**Issue by BenMake** [TenkyuChimata/SCEEW#1]
希望能提前获取到其他城市的地震预警数据， 这个数据源找了很久没合适的

中国地震台API：http://www.ceic.ac.cn/ajax/ 延迟太多无法及时预警
成都减灾所的非公开API：https://mobile.chinaeew.cn/ HTTP 拉取会给服务器挺大压力 

同样在搞Python地震预警模块： linux无UI，纯音频报警 +1

**Comment by TenkyuChimata** [comment]
成都减灾所的就可以，提供全国范围内的预警
但是不建议使用，因为涉及到版权问题，而且他们服务器本来就很糟糕，稍微大点的地震响应就会很慢
