### ISSUE TITLE
软件打开后无任何窗口

### ISSUE THREAD

**Issue by Aloys233** [TenkyuChimata/SCEEW#2]
是bug么，系统版本：win11 22h2

**Comment by TenkyuChimata** [comment]
确认是最新版本v1.0.5嘛，如果是请检查下软件目录下的errors.log文件是否有内容，如果有麻烦发上来。

**Comment by Aloys233** [comment]
有个error文件，但现在他又打的开了
[errors.log](https://github.com/TenkyuChimata/SCEEW/files/12444845/errors.log)

**Comment by Aloys233** [comment]
对了，能不能弄个任务栏图标？

**Comment by TenkyuChimata** [comment]
看了下错误日志，单纯只是因为本地连接外网的水平比较差。
如果支持ipv6的话，可以去hosts添加
2606:4700:4700::1001 api.wolfx.jp
能够很大程度上的改善网路问题

关于状态栏图标，个人认为完全没有必要，因为软件本身就不存在后台，只有一个前台窗口，退出了就彻底关闭了，平时最小化到任务栏就行。

**Comment by TenkyuChimata** [comment]
如果没有更进一步的问题就先close了

**Comment by TenkyuChimata** [comment]
> 看了下错误日志，单纯只是因为本地连接外网的水平比较差。
> 
> 如果支持ipv6的话，可以去hosts添加
> 
> 2606:4700:4700::1001 api.wolfx.jp
> 
> 能够很大程度上的改善网路问题
> 
> 
> 
> 关于状态栏图标，个人认为完全没有必要，因为软件本身就不存在后台，只有一个前台窗口，退出了就彻底关闭了，平时最小化到任务栏就行。

提醒一下，这个方法已经失效了，目前修改反而会导致请求出错，现在不再需要修改hosts也可以有较快的请求速度
