### ISSUE TITLE
地震烈度计算公式有问题

### ISSUE THREAD

**Issue by chengtingting980903** [TenkyuChimata/SCEEW#4]
您写的：cnshindo = max(1.92 + 1.63 * magnitude - 3.49 * math.log(eqdistance, 10), 0.0)
其中1.92应该是0.92吧，公式应该是这个I=0.92+1.63M-3.49logR。

**Comment by TenkyuChimata** [comment]
你好，没问题的，网上给出的烈度衰减公式确实是0.92, 但本人的这个公式是根据取舍后与ICL算出的烈度最接近的。

**Comment by chengtingting980903** [comment]
好的，感谢回答

**Comment by CHN-STUDENT** [comment]
各位好，请问这个经验公式是否能够运用中国其他省份（如新疆、青海）等地，我们需要通过API获取信息做避险预警，目前有两种方案：1. 计算震中和受影响单位距离（100KM），不管震级直接报警；2. 按照经验公式推算地震烈度是否对受影响单位影响
由于本人非地震专业研究人士，不知道这个策略和算法是否合适，欢迎告知谢谢！
